import React from 'react'

function PrivacyAndPolicy() {
  return (
    <div className="p-4 sm:p-6 md:p-10 lg:p-16">
    <div className="max-w-5xl mx-auto bg-white shadow-lg rounded-xl p-6">
      <h1 className="text-lg sm:text-xl md:text-2xl text-blue-500 font-bold mb-5 text-center">
        Privacy Policy
      </h1>
      <p className="text-sm sm:text-base leading-relaxed mb-5">
        (“we,” “our,” or “us”, or “EL”) is committed to protecting your privacy. This Privacy Policy explains how your personal information is collected, used, and disclosed by Easy Labour. This Privacy Policy applies to our website, digitallabourchowk.com, and its associated subdomains (collectively, our “Service”) alongside our application, Easy Labour Rojzar, Easy Labour Business, Easy Labour Partner. By accessing or using our Service, you signify that you have read, understood, and agree to our collection, storage, use, and disclosure of your personal information as described in this Privacy Policy and our Terms of Service.
      </p>

      <h2 className="text-lg sm:text-xl md:text-2xl font-bold text-blue-500 mb-5">
        Definitions and key terms
      </h2>
      <ul className="list-disc space-y-4 pl-5">
        <li>
          <span className="font-semibold">Cookie: </span>
          small amount of data generated by a website and saved by your web browser. It is used to identify your browser, provide analytics, remember information about you such as your language preference or login information.
        </li>
        <li>
          <span className="font-semibold">Company: </span>
          when this policy mentions “Company,” “we,” “us,” or “our,” it refers to Gaudrika Easy Labour, 197, 1st floor, Ami, Telhan, Bihar that is responsible for your information under this Privacy Policy.
        </li>
        <li>
          <span className="font-semibold">Country: </span>
          where Easy Labour Rojzar, Easy Labour Business, Easy Labour Partner or the owners/founders of Easy Labour Rojzar, Easy Labour Business, Easy Labour Partner are based, in this case is India.
        </li>
        <li>
          <span className="font-semibold">Customer: </span>
          refers to the company, organization or person that signs up to use the Easy Labour Rojzar, Business & Partner Service to manage the relationships with your consumers or service users.
        </li>
        <li>
          <span className="font-semibold">Device: </span>
          any internet connected device such as a phone, tablet, computer or any other device that can be used to visit Easy Labour Rojzar, Business & Partner and use the services.
        </li>
        <li>
          <span className="font-semibold">IP address: </span>
          Every device connected to the Internet is assigned a number known as an Internet protocol (IP) address. These numbers are usually assigned in geographic blocks. An IP address can often be used to identify the location from which a device is connecting to the Internet.
        </li>
        <li>
          <span className="font-semibold">Personnel: </span>
          refers to those individuals who are employed by Easy Labour Rojzar, Business & Partner or are under contract to perform a service on behalf of one of the parties.
        </li>
        <li>
          <span className="font-semibold">Personal Data: </span>
          any information that directly, indirectly, or in connection with other information — including a personal identification number — allows for the identification or identifiability of a natural person.
        </li>
        <li>
          <span className="font-semibold">Service: </span>
          refers to the service provided by Easy Labour Rojzar, Business & Partner as described in the relative terms (if available) and on this platform.
        </li>
        <li>
          <span className="font-semibold">Website: </span>
          Easy Labour Rojzar, Business & Partner’s site, which can be accessed via this URL: easylabour.com.
        </li>
        <li>
          <span className="font-semibold">You: </span>
          a person or entity that is registered with Easy Labour Rojzar, Business & Partner to use the Services.
        </li>
      </ul>
    </div>
  </div>
  )
}

export default PrivacyAndPolicy